# Generated by Django 4.2.1 on 2023-06-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_activitycategory_activitylog_administrator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
